server:
  port: 8084

spring:
  application:
    name: parser
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: parser-consumer-group
  datasource:
    url: jdbc:mysql://localhost:3306/capstone_db
    username: capstone
    password: capstone
  jpa:
    hibernate:
      ddl-auto: update

parser:
  kafka:
    topic: jfc_parser

logging:
  level:
    org:
      apache:
        kafka: ERROR
      springframework:
        kafka: ERROR
    kafka: ERROR
